// גורל העשיריות — מנוע חישוב ותצוגה

const GORAL_PRAYER = 'קודם הגורל יאמר תפלה זו: יהי רצון מלפניך יֶהֹוֹהִ אלהי ואלהי אבותי, אלהי אברהם אלהי יצחק ואלהי יעקב, שתקשיב לתפלתי, ותתני לחן ולחסד ולרחמים בעינך לעשות בקשתי בזה הגורל, כמו שאמרת "אך בגורל יחלק את הארץ" (במדבר כו, נה), לך יהוה הרחמים והסליחות, ולנו בושת הפנים על כל מה שהכעסתיך במעשי הרעים, כי אתה יצרתני עפר מן האדמה ונפחת בי נשמה, והוצאתני לאוויר העולם, ועתה באתי לפניך בלב נשבר ובלב נדכה, שתודיעני מה שישאל ממני בזה הגורל, שחנוניך הם חנונים, ורחומיך הם רחומים, שתשמיעני ותוציא הדבר לאמיתו, והבה לי תמים ושלח לי במחשבתי דברי שאלתי באופן שהגורל הזה יענה תשובה אמיתית כי אין לנו אורים ותומים בעוונותינו, ולכן קראתי לעליונים ולתחתונים שיעתירו בעדי ויפילו תחנונים לאדוני האדונים, יהוה אלהים יעזור לי. ותאמר ג\' פעמים פסוק "אברך את ה\' אשר יעצני אף לילות יסרוני כליותי" (תהלים טז, ז) וכן ג\' פעמים "גורלך תפיל בתוכנו" (משלי א, יד), אמן סלה ועד.';

const G_AB={1:"א",2:"ב",3:"ג",4:"ד",5:"ה",6:"ו",7:"ז",8:"ח",9:"ט",10:"י",11:"כ",12:"ל",13:"מ",14:"נ",15:"ס",16:"ע",17:"פ",18:"צ",19:"ק",20:"ר",21:"ש",22:"ת"};
const G_TABLES={א:{gsv:8,len:17,seq:[{t:"w",v:"אל",s:null},{t:"w",v:"יצא",s:13},{t:"w",v:"אשר",s:null},{t:"w",v:"לו",s:null},{t:"w",v:"שמה",s:10},{t:"w",v:"הגורל",s:8},{t:"n",v:2},{t:"n",v:12},{t:"n",v:17},{t:"w",v:"גורלי",s:null},{t:"n",v:13},{t:"n",v:12},{t:"w",v:"תומך",s:null},{t:"n",v:12},{t:"n",v:1},{t:"n",v:5},{t:"w",v:"יהי",s:null}]},ב:{gsv:2,len:13,seq:[{t:"n",v:2},{t:"n",v:12},{t:"w",v:"אדני",s:null},{t:"w",v:"יצא",s:null},{t:"n",v:16},{t:"w",v:"הגורל",s:null},{t:"w",v:"לו",s:null},{t:"n",v:13},{t:"w",v:"תומך",s:null},{t:"w",v:"גורלי",s:null},{t:"n",v:13},{t:"n",v:1},{t:"n",v:7}]},ג:{gsv:4,len:27,seq:[{t:"n",v:12},{t:"n",v:14},{t:"w",v:"גורלי",s:null},{t:"n",v:12},{t:"n",v:11},{t:"n",v:22},{t:"n",v:11},{t:"n",v:5},{t:"n",v:22},{t:"n",v:12},{t:"w",v:"אדני",s:null},{t:"n",v:22},{t:"n",v:12},{t:"n",v:20},{t:"w",v:"תומך",s:null},{t:"n",v:12},{t:"w",v:"אתה",s:null},{t:"n",v:5},{t:"w",v:"וכוסי",s:null},{t:"n",v:22},{t:"n",v:11},{t:"n",v:5},{t:"n",v:22},{t:"n",v:11},{t:"w",v:"גורלי",s:null},{t:"n",v:14},{t:"n",v:12}]},ד:{gsv:6,len:25,seq:[{t:"n",v:6},{t:"n",v:1},{t:"n",v:1},{t:"w",v:"גורלי",s:null},{t:"n",v:1},{t:"n",v:7},{t:"n",v:1},{t:"n",v:12},{t:"n",v:5},{t:"w",v:"אדני",s:null},{t:"n",v:18},{t:"n",v:22},{t:"n",v:2},{t:"n",v:18},{t:"n",v:22},{t:"w",v:"מנת",s:null},{t:"n",v:12},{t:"n",v:14},{t:"n",v:12},{t:"n",v:18},{t:"n",v:12},{t:"n",v:5},{t:"n",v:12},{t:"n",v:1},{t:"n",v:1}]}};
const G_VALS={even:{א:8,ב:2,ג:4,ד:6},odd:{א:9,ב:1,ג:3,ד:5}};
function _gsv(e){return e.t==="n"?e.v:e.s;}
function _el(id){return document.getElementById(id);}
function goralBuildRow1(n,f,q){const t=(n+' בן '+f+' '+q).trim();const w=t.split(/\s+/).filter(Boolean);const lc=w=>[...w].filter(c=>/[\u05D0-\u05EA]/.test(c)).length||w.length;return[w.length,...w.map(lc)];}
function goralBuildTriangle(row){const t=[row.slice()];let cur=row;while(cur.length>1){const nxt=[];for(let i=0;i<cur.length-1;i++){let s=cur[i]+cur[i+1];if(s===18){nxt.push(18);continue;}while(s>9)s-=9;nxt.push(s||9);}t.push(nxt);cur=nxt;}return t;}
function goralGetDiagonals(tri){const apex=tri[tri.length-1][0];const even=apex%2===0;const ok=n=>n%2===(even?0:1);const d=tri.map(r=>r[r.length-1]).filter(ok);const t=tri[0].filter(ok);return[...new Set([...d,...t])].slice(0,4);}
function goralNavigate(key,gv){const tbl=G_TABLES[key];const seq=tbl.seq,len=tbl.len;let si=seq.findIndex(e=>_gsv(e)===gv);if(si<0)si=0;const signs=[],seen=new Set([si]);let cur=si;for(let k=0;k<len;k++){const nx=(cur+10)%len;if(nx===si||seen.has(nx))break;seen.add(nx);cur=nx;const val=_gsv(seq[nx]);if(val===null||val===undefined)break;signs.push(val);}return signs;}
function goralRunCalc(name,father,q){const row1=goralBuildRow1(name,father,q);const triangle=goralBuildTriangle(row1);const apex=triangle[triangle.length-1][0];const parity=apex%2===0?'even':'odd';const diags=goralGetDiagonals(triangle);const keys=['א','ב','ג','ד'];const tRes={};keys.forEach(k=>{const gv=G_VALS[parity][k];const signs=goralNavigate(k,gv);const letters=signs.map(s=>G_AB[s]||'').join('');tRes[k]={signs,letters};});const words=keys.map(k=>tRes[k].letters).filter(Boolean);const answer=words.length>=4?words[0]+' '+words[1]+' '+words[2]+' יעזור '+words[3]+' אשר שואל ותבטל רצונך':words.join(' ');return{row1,triangle,apex,parity,diags,tRes,answer};}
let _goralResult=null,_prayerOpen=false;
function goralShowStage(s){['intro','form','calc','result'].forEach(x=>{const e=_el('goral-stage-'+x);if(e)e.style.display=x===s?'':'none';});window.scrollTo(0,0);}
function goralTogglePrayer(){_prayerOpen=!_prayerOpen;const e=_el('goralPrayerText'),b=_el('goralPrayerBtn');if(e)e.style.display=_prayerOpen?'':'none';if(b)b.innerHTML=(_prayerOpen?'▼':'◀')+' תפילה לפני הפלת הגורל';}
function goralReset(){_el('goralName').value='';_el('goralFather').value='';_el('goralQuestion').value='';_el('goralFormError').style.display='none';_goralResult=null;goralShowStage('intro');}
async function goralSubmit(){const name=_el('goralName').value.trim(),father=_el('goralFather').value.trim(),question=_el('goralQuestion').value.trim(),err=_el('goralFormError');if(!name||!father||!question){err.style.display='block';return;}err.style.display='none';const result=goralRunCalc(name,father,question);_goralResult=result;goralShowStage('calc');const display=_el('goralTriDisplay'),progress=_el('goralProgress');display.innerHTML='';const MAX=13;for(let i=0;i<=result.triangle.length;i++){await new Promise(r=>setTimeout(r,i===0?450:95));if(progress)progress.style.width=Math.round(i/result.triangle.length*100)+'%';const rows=result.triangle.slice(0,i),from=Math.max(0,rows.length-MAX),vis=rows.slice(from);display.innerHTML=vis.map((row,ri)=>{const gi=from+ri,isApex=gi===result.triangle.length-1,isNew=ri===vis.length-1;const cs=isApex?'background:linear-gradient(135deg,#C9A84C,#9A7A06);color:#FFF5E0;border:none;box-shadow:0 2px 8px rgba(180,150,10,.4)':isNew?'background:#E8DDD0;color:#2C2420;border:1px solid #D8CEBC':'background:#fff;color:#2C2420;border:1px solid #E0D8CC';return'<div style="display:flex;gap:4px;animation:goralRowIn .2s ease">'+row.map(n=>'<span style="min-width:28px;height:28px;padding:0 3px;display:inline-flex;align-items:center;justify-content:center;border-radius:6px;font-size:11px;font-weight:700;'+cs+'">'+n+'</span>').join('')+'</div>';}).join('');}await new Promise(r=>setTimeout(r,600));goralRenderResult();goralShowStage('result');}
function goralRenderResult(){const r=_goralResult;if(!r)return;const keys=['א','ב','ג','ד'],cont=_el('goralResultContainer');cont.innerHTML='<div style="background:#1A1A28;border-radius:16px;padding:26px 20px;margin-bottom:16px;text-align:center"><p style="color:#C9A84C;font-size:.72rem;letter-spacing:3px;margin:0 0 12px;font-weight:400">נוסח הגורל</p><p style="color:#FFF5E0;font-size:1.25rem;font-weight:700;line-height:1.85;margin:0">'+r.answer+'</p></div><div class="card" style="margin-bottom:14px"><div class="card-title" style="font-size:.8rem">✦ פירוט ארבעת הלוחות</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">'+keys.map(k=>{const tr=r.tRes[k];return'<div style="background:var(--bg,#EAE5DC);border-radius:10px;padding:12px 10px;border:1px solid var(--border,#D8CEBC)"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px"><span style="color:var(--muted,#7A6E62);font-size:.72rem">לוח '+k+'</span><span style="color:#C8C0B0;font-size:.68rem">'+tr.signs.join('—')+'</span></div><div style="color:#B8950A;font-size:1.6rem;font-weight:900;letter-spacing:4px;line-height:1">'+(tr.letters||'—')+'</div></div>';}).join('')+'</div></div><div class="card" style="margin-bottom:14px"><div class="card-title" style="font-size:.8rem">מספרי האלכסון ('+(r.parity==='even'?'זוגיים':'אי-זוגיים')+')</div><div style="display:flex;gap:10px;justify-content:center;padding:4px 0">'+r.diags.map(d=>'<div style="width:44px;height:44px;border-radius:10px;background:#1A1A28;color:#D4AF37;font-size:1.2rem;font-weight:700;display:flex;align-items:center;justify-content:center;">'+d+'</div>').join('')+'</div></div><div class="card" style="border-right:3px solid #B8950A;margin-bottom:16px"><p style="color:var(--muted,#7A6E62);font-size:.72rem;margin:0 0 4px">שאלה</p><p style="color:var(--text,#2C2420);font-size:.88rem;margin:0;line-height:1.7">'+_el('goralName').value+' בן '+_el('goralFather').value+': &ldquo;'+_el('goralQuestion').value+'&rdquo;</p></div><button class="btn btn-gold" onclick="goralReset()">✦ שאלה חדשה</button>';}